// Generated by intersync. Hand-edits to existing modules are preserved on merge.
import type { StudyModule } from './types'

export const modules = [
  {
    "id": "01",
    "title": "Implement Fraud Detection Pipeline",
    "status": "in-progress",
    "goal": "To implement a sophisticated fraud detection pipeline capable of analyzing message contents and URLs to identify potential scams.",
    "tasks": [
      "Develop the fraud detection pipeline with various stages of analysis.",
      "Implement messaging signal detection based on urgency, threat, and other criteria.",
      "Integrate URL intelligence checks for domain validation and trust assessment.",
      "Score evidence to classify risk levels and infer scam types."
    ],
    "concept": "Security and Detection",
    "sonaMapping": "",
    "studyPath": [
      "Introduction to Security",
      "Threat Detection Mechanisms",
      "Implementing Scoring Models"
    ],
    "questions": [
      {
        "question": "What is the role of 'detectMessageSignals' in the pipeline?",
        "answer": "'detectMessageSignals' identifies evidence from message contents based on predefined patterns and assigns points and severity."
      },
      {
        "question": "How are URLs analyzed in this implementation?",
        "answer": "URLs are parsed and checked against trusted domains, potential abuses, and mismatches to gather evidence of risks."
      }
    ],
    "completionQuestions": [
      {
        "question": "How does the pipeline classify risk levels?",
        "answer": "Risk levels are classified based on a scoring system that considers both individual and combined evidence effects."
      },
      {
        "question": "What factors influence the confidence estimation of scam detection?",
        "answer": "The number of detector families, critical signals, and presence of URLs influence the confidence estimation in analysing scams."
      }
    ],
    "files": [
      "src/security/pipeline.js",
      "src/security/risk-policy.js",
      "src/security/signals.js",
      "src/security/url-intelligence.js"
    ]
  },
  {
    "id": "02",
    "title": "Enhance Package Scripts",
    "status": "complete",
    "goal": "To add a test script to the package.json for executing the test suite using Node.js.",
    "tasks": [
      "Modify package.json to include a test script entry.",
      "Ensure compatibility of the test script with the existing project setup."
    ],
    "concept": "Project Configuration",
    "sonaMapping": "",
    "studyPath": [
      "Node.js Scripting",
      "Vite Project Setup",
      "Continuous Integration"
    ],
    "questions": [
      {
        "question": "What command was added to package.json?",
        "answer": "A 'test' command was added to execute tests using 'node --test'."
      }
    ],
    "completionQuestions": [
      {
        "question": "Why is adding a testing script beneficial for a project?",
        "answer": "It ensures that tests can be run consistently across environments, facilitating automated testing and continuous integration."
      }
    ],
    "files": [
      "package.json"
    ]
  }
] satisfies StudyModule[]
